home work #2
js-tasks-ru/js-20230223_stepkin-alexander pull request #2
Opened 2023-03-01 15:43 UTC by rambowGit

Добавлено решение для ДЗ#2: sortStrings, pick, omit

2023-03-01 15:44 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 12:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let collator = new Intl.Collator("ru", { caseFirst: "upper" });
`const`

2023-03-02 12:28 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +		return arrCopy.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-03-02 12:29 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +			tmpArray.push([key, value]);
может сразу сохранять в объект?

2023-03-02 12:29 UTC, dosandk requested changes
решение sortStrings следует поправить

2023-03-02 13:50 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-02 14:01 UTC, rambowGit commented
Исправил: https://github.com/js-tasks-ru/js-20230223_stepkin-alexander/pull/2/commits/f7df73791fd7bc1b4088e8eba00b802f92213bdf

2023-03-02 14:05 UTC, rambowGit commented on 02-javascript-data-types/2-pick/index.js
> +			tmpArray.push([key, value]);
@dosandk, чет у меня не взлетело.
```if (fields.includes(key)``` вот это вынес в отдельную функцию sortKeys - callback для map()
Но если пишу вот так, то не работает правильно:
Object.fromEntries(Object.entries(obj).map(sortKeys))

2023-03-05 10:58 UTC, dosandk approved these changes
👍 good

2023-03-05 10:58 UTC, merged