07-async-code-fetch-api-part-1
js-tasks-ru/js-20230223_stepkin-alexander pull request #7
Opened 2023-03-24 18:13 UTC by rambowGit

Некоторые тесты не проходят.
Но в целом все работает

2023-03-24 18:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-26 12:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-26 15:45 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.url = new URL(url, BACKEND_URL);
👍 good 
лайк за `new URL`

2023-03-26 15:45 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.update();
good 👍

2023-03-26 15:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.value = valluesArray.reduce((acc, curValue) => acc + curValue, initialValue);
а зачем константа?
сразу проинициализируйте вот так:

```js
valluesArray.reduce((acc, curValue) => acc + curValue, 0);
```
Это тот случай когда 0 не является "magic number"

2023-03-26 15:47 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +  async loadData(from, to) {
good 👍

2023-03-26 15:59 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  this.sort();
Так делать не следует!
Нужно сразу задать сортировку при запросе на сервер.

2023-03-26 15:59 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +			<div data-element="header" class="sortable-table__header sortable-table__row">
что случилось с форматированием кода?

2023-03-26 15:59 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  console.log("data: ", data);
не оставляйте отладочные консоли, перед коммитом внимательно просматривайте изменения!

2023-03-26 16:00 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +					${this.getTableRow(item)}
🔴 поправьте форматирование!
1 таб = 2 пробела

2023-03-26 16:00 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  const responce = await fetch(this.url);
пожалуйста используйте `fetchJson`

2023-03-26 16:00 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  let options = {
почему `options` это `let`?

2023-03-26 16:01 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  return new IntersectionObserver(callback, options);
good 👍
лайк за использование `IntersectionObserver`

2023-03-26 16:01 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	async onScroll() {
почему данный метод `async` без `await` внутри?
может он не должен быть `async`?

2023-03-26 16:02 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  let headerItem = this.headerConfig.find(headerItem => this.sorted.id === headerItem.id);
`const`!

2023-03-26 16:03 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	updateArrow() {
пожалуйста посмотрите логику перемещение стрелки в последней домашке по `SortableTable` к-ю мы разобрали

2023-03-26 16:03 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  let arrCopy = [...this.data];
почему `let`?

2023-03-26 16:04 UTC, dosandk commented on 07-async-code-fetch-api-part-1/2-sortable-table-v3/index.js
> +	  if (sortType === 'string') {
подумайте как упростить данный кусок кода 
строки 316-333

2023-03-26 16:05 UTC, dosandk requested changes
! Решение `SortableTable` следует поправить согласно замечаний, дать ответы на вопросы

2023-03-27 09:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-27 13:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-27 13:30 UTC, rambowGit commented
> ! Решение `SortableTable` следует поправить согласно замечаний, дать ответы на вопросы

@dosandk , поправил. Но ошибки в тестах никуда не делись.
Наверное, нужно сильнее поправить )

2023-03-27 16:10 UTC, dosandk approved these changes
👍 good

2023-03-27 16:11 UTC, merged